### ISSUE TITLE
Details drawer

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#701]
* [x]  accessibility not considered. should probably be replaced with a html dialog or a radix sidebar component. #678
* [x] on mobile it overflows so it cannot be seen
* [x] The dark background doesn't show when zoomed out on mobile
* [x] Showing stale data #670
* [x] too wide for occurrences, the space isnt' used by the layout.
* [x] arrow keys not working #665
* [x] esc keys not working #664
* [x] focus not returned to trigger #666
* [x] focus trap not working #667
* [x] Data header shouldn't be included in drawer, only on standalone page

Can wait for gbif.org iteration
* [ ] Option to define tab to open on (images, cluster, ...)? Or at least remember the last used in drawer.
* [x] small: I find it annoying that the overlay is animated left right instead of just covering the whole screen immedately

**Comment by danielvdm2000** [comment]
@MortenHofft A title and description is required to make the dialog accessible. What do you think would make sense to include here for occurrences?

**Comment by danielvdm2000** [comment]
This task "Data header shouldn't be included in drawer, only on standalone page" has been moved to https://github.com/gbif/gbif-web/issues/422
